name: Azure WSL setup
description: 'Allocate and connect to an Azure VM with WSL ready.'

inputs:
  az_name:
    description: Name of the Azure VM to run on
    required: true
  az_resource_group:
    description: Name of the Azure resource group to run on
    required: true
  az_creds:
    description: Credentials to use for Azure
    required: true

runs:
  using: 'composite'
  steps:
    - uses: azure/login@v1
      with:
        creds: ${{ inputs.az_creds }}
    - name: Start the Runner
      shell: bash
      run: |
        az vm start --name ${{ inputs.az_name }} --resource-group ${{ inputs.az_resource_group }}

branding:
  icon: 'arrow-up-circle'
  color: 'purple'