name: Azure WSL repo clone
description: 'Clones your repo into WSL.'

inputs:
  distro:
    description: Which (installed) distro to use
    required: true
  working-dir:
    description: Where the repo should be cloned
    required: false
    default: "."

runs:
  using: 'composite'
  steps:
    - name: Clone repo
      uses: ./.github/actions/wsl-powershell
      with:
        max-attempts: 5
        exec: |
          $env:WSL_UTF8=1

          wsl.exe -d ${{ inputs.distro }} --cd "~" -- bash -ec @'
          mkdir -p ${{ inputs.working-dir }}
          git clone -q https://github.com/${{ github.repository }}.git ${{ inputs.working-dir }}
          cd ${{ inputs.working-dir }}
          git fetch -q --no-tags --prune origin +${{ github.sha }}:${{ github.ref }}
          git checkout -q ${{ github.sha }}
          '@

          if ( ! $? ) { Exit(1) }