name: Install Ubuntu WSL
description: 'Install WSL from the store'

inputs:
  distro_name:
    description: Distro name as shown in 'wsl -l -v'. Leave blank to install no distro.
    required: true
    default: Ubuntu
  distro_launcher:
    description: The chosen distro's launcher executable.
    required: true
    default: ubuntu.exe
  distro_store_name:
    description: The chosen distro's name in the Windows Store.
    required: true
    default: Ubuntu

runs:
  using: 'composite'
  steps:
    - name: Install or update WSL
      uses: ubuntu/WSL/.github/actions/wsl_enabled_powershell/@main
      with:
        exec: |
          Write-Output '::group::Install WSL'
          # Install or update WSL
          winget install --name 'Windows Subsystem for Linux' --accept-source-agreements --accept-package-agreements --silent
          $exit=$LASTEXITCODE

          Write-Output '::endgroup::'
          if ( "${{ inputs.distro_name }}" -eq "$null" ) {
            Exit($exit)
          }

          Write-Output '::group::Install and register the distro'
          # Install or update Appx
          winget install --name '${{ inputs.distro_store_name }}'  --accept-source-agreements  --accept-package-agreements --silent
          Write-Output '::endgroup::'

          # Unregister any pre-exising distro
          $env:WSL_UTF8=1
          wsl.exe --unregister ${{ inputs.distro_name }} 2>&1 | Out-Null

          # Register a new instance
          ${{ inputs.distro_launcher }} install --root --ui=none

          # Testing succesful install
          ${{ inputs.distro_launcher }} run echo Created a new distro with user: '$(whoami)'
          $exit=$LASTEXITCODE

          Write-Output '::endgroup::'
          Exit($exit)