name: Azure RDP setup
description: 'Connect via RDP in order to log in as session other than 0.'

inputs:
  az_vm_hostname:
    description: Hostname for "xfreerdp /v:az_vm_hostname"
    required: true
  az_vm_username:
    description: Username for "xfreerdp /u:az_vm_username"
    required: true
  az_vm_password:
    description: Password for "xfreerdp /p:az_vm_password"
    required: true

runs:
  using: 'composite'
  steps:
    - name: rdp
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        MAX_CONNECTION_ATTEMPTS: "10"
      run: |
        set -euo pipefail

        echo "::group::Dependencies"
        sudo apt-get update -y
        sudo apt-get install -y xvfb freerdp2-x11
        echo "::endgroup::"

        # detected empirically and confirmed here: https://github.com/FreeRDP/FreeRDP/blob/68ad8d5a1c8d52828095c2293acea1c76fa7fcb5/client/X11/xfreerdp.h#L350
        vmOfflineErrorCode=141

        lastExitCode=${vmOfflineErrorCode}
        attemptCount=0
        while [[ ${attemptCount} -lt ${MAX_CONNECTION_ATTEMPTS} ]]; do
          ((++attemptCount))

          echo "::group::RDP connection: Attempt ${attemptCount}"

          xvfb-run -a xfreerdp                          \
            /v:"${{ inputs.az_vm_hostname }}"           \
            /u:"${{ inputs.az_vm_username }}"           \
            /p:"${{ inputs.az_vm_password }}"           \
            /cert:tofu                                  \
            | tee /tmp/rdp.log                          \
            | grep -v "${{ inputs.az_vm_hostname }}"    \
            || lastExitCode=$?

          echo "::endgroup::"

          if [[ ${lastExitCode} -ne ${vmOfflineErrorCode} ]]; then
            echo "::group::RDP logs"
            cat /tmp/rdp.log || echo "Failed to retrieve log"
            echo "::endgroup::"
            
            echo "Connection finished with exit code ${lastExitCode}"
            exit 0
          fi

          sleep 20
        done

        echo "Error: connection failed too many times"
        exit 1

branding:
  icon: 'cast'
  color: 'purple'
