name: WSL-enabled powershell
description: 'Execute a script in powershell as session >= 2.'

inputs:
  exec:
    description: Script to execute
    required: true
  max-attempts:
    description: Maximum number of connection attempts 
    default: "20"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Clean up workdir
      shell: powershell
      run: |
        Write-Output "::group::Cleaning up workdir"
        if( $(Test-Path -Path ".\exitCode.log") ) {
          Remove-Item -Path ".\exitCode.log" -Force | Out-Null
        }
        if( $(Test-Path -Path ".\output.log") ) {
          Remove-Item -Path ".\output.log" -Force | Out-Null
        }
        if( $(Test-Path -Path ".\path.txt") ) {
          Remove-Item -Path ".\path.txt" -Force | Out-Null
        }
        if( $(Test-Path -Path ".\script.txt") ) {
          Remove-Item -Path ".\script.ps1" -Force | Out-Null
        }
        Write-Output "::endgroup::"
        Exit(0)

    - name: Execute the script
      shell: powershell
      env:  
        exec: ${{ inputs.exec }}
      run: |
        Write-Output "::group::Connecting via RDP"
        $higherSession=0
        $count=0
        While (${higherSession} -lt "2") {
          Start-Sleep 5
          $count = $count + 1
          If ($count -gt ${{ inputs.max-attempts }}) {
            Write-Output "::endgroup::"
            Write-Output "Error: RDP never connected"
            Exit (-1)
          }
          Write-Output "Attempting to connect via RDP. Attempt ${count} out of ${{ inputs.max-attempts }}."

          $sessions=$(C:\SysinternalsSuite\logonsessions.exe -nobanner | Select-String Session: | Sort-Object -Descending | Get-Unique)
          If ( $null -ne $sessions -and $sessions.length -gt 0 ) {
            $higherSession=$( $sessions )[0].ToString()[-1]
          }
        }
        Write-Output "Connection succeeded"
        Write-Output "::endgroup::"

        Write-Output "::group::Running script"
        Write-Output "Running script. Output will be shown after execution has finished."
        
        # Creating script file
        New-Item -Force -Path "script.ps1" | Out-Null
        $script=( Write-Output "script.ps1" | Resolve-Path )
        [IO.File]::WriteAllLines( "script.ps1" , "${env:exec}")

        # Storing path
        New-Item -Force -Path "path.txt" | Out-Null
        [IO.File]::WriteAllLines( 'path.txt' , "${env:Path}")

        c:\sysinternalssuite\psexec.exe -nobanner -accepteula -w $PWD.Path -i $higherSession powershell.exe -Command @"
        `${env:Path}="`${env:Path};`$(Get-Content path.txt)"
        powershell.exe -File script.ps1 3>&1 2>&1 | Out-File -File .\output.log
        Write-Output `$LASTEXITCODE > .\exitCode.log
        "@

        $exit=$(Get-Content ".\exitCode.log")
        Write-Output "::endgroup::"
        Exit ($exit)

    - name: Retrieve logs
      if: always()
      shell: powershell
      run: Get-Content ".\output.log"

branding:
  icon: 'monitor'
  color: 'purple'
