name: WSL-enabled powershell
description: 'Execute a script in powershell as session >= 2.'

inputs:
  exec:
    description: Script to execute
    required: true
  max-attempts:
    description: Maximum number of connection attempts 
    default: "20"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Execute the script
      shell: powershell
      env:
        exec: ${{ inputs.exec }}
      run: |
        Write-Output "::group::Connecting via RDP"
        $higherSession=0
        $count=0
        While (${higherSession} -lt "2") {
          Start-Sleep 5
          $count = $count + 1
          If ($count -gt ${{ inputs.max-attempts }}) {
            Write-Output "::endgroup::"
            Write-Output "Error: RDP never connected"
            Exit (-1)
          }
          Write-Output "Attempting to connect via RDP. Attempt ${count} out of ${{ inputs.max-attempts }}."

          $sessions=$(C:\SysinternalsSuite\logonsessions.exe -nobanner | Select-String Session: | Sort-Object -Descending | Get-Unique)
          If ( $null -ne $sessions -and $sessions.length -gt 0 ) {
            $higherSession=$( $sessions )[0].ToString()[-1]
          }
        }
        Write-Output "Connection succeeded"
        Write-Output "::endgroup::"

        Write-Output "::group::Running script"
        Write-Output "Running script. Output will be shown after execution has finished."
        $script="script.ps1"
        New-Item -Force -Path "${script}" | Out-Null
        $script=( Write-Output "${script}" | Resolve-Path )
        [IO.File]::WriteAllLines( "${script}" , "${env:exec}")

        c:\sysinternalssuite\psexec.exe -nobanner -accepteula -w $PWD.Path -i $higherSession powershell -Command @"
        powershell -File ${script} 3>&1 2>&1 | Out-File -File .\output.log
        Exit(`$LASTEXITCODE)
        "@

        $exit=$LASTEXITCODE
        Write-Output "::endgroup::"

        # The logs themselves should contain the ::group:: directives
        Get-Content ".\output.log"

        Exit ($exit)

branding:
  icon: 'monitor'
  color: 'purple'
