name: Test event trigger
on:
  workflow_dispatch:
    inputs:
      wslID:
        description: 'Release name to use for the bundle'
        required: false
        default: 'local'
      rootfses:
        description: 'Ubuntu WSL rootfs urls, separated by a semi colon. Direct set of "tar.gz::arch" if arch is not in the filename'
        required: true
        default: 'http://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64-wsl.rootfs.tar.gz'

jobs:
  build-matrix:
    name: Build Matrix for WSLIDs to run on with rootfses, which can be manually supplied or automatically.
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix-release.outputs.matrix }}
    steps:
      - name: Build Matrix for WSLIDs to run on with rootfses, which can be manually supplied or automatically
        id: build-matrix-release
        run: |
          set -eux
          # Manual build
          if [ ${{ github.event_name }} = 'workflow_dispatch' ]; then
            wslID="${{ github.event.inputs.wslID }}"
            if [ -z "${wslID}" ]; then
              wslID="Ubuntu-Preview"
            fi

            builds="$(cat <<-EOF
              {"input":
                [
                  {
                    "wslID": "${wslID}",
                    "rootfses": "${{ github.event.inputs.rootfses }}",
                    "upload": "no"
                  }
                ]
              }
          EOF
            )"
          fi

          echo "${builds}"
          echo "::set-output name=matrix::${builds}"
