name: Example action using wsl-exec

on:
  workflow_dispatch:

jobs:
  example:  
    uses: ./.github/workflows/wsl-exec.yaml
    secrets:
      az_creds: ${{ secrets.AZURE_VM_CREDS }}
      az_vm_hostname: ${{ secrets.AZURE_VM_AUTHORITY }}
      az_vm_username: ${{ secrets.AZURE_VM_UN }}
      az_vm_password: ${{ secrets.AZURE_VM_UP }}
    with:
      az_name: wsl-ci
      az_resource_group: wsl
      exec: |
        echo "::group::Echoing"
        echo "Hello, world!"
        echo "::endgroup::"

        echo "::group::Distro info"
        lsb_release -a
        echo "::endgroup::"

        echo "::group::Current directory contents"
        ls -lAh
        echo "::endgroup::"
