name: Example action using wsl-exec

on:
  workflow_dispatch:
  pull_request:

jobs:
  example:  
    uses: ./.github/workflows/wsl-exec.yaml
    secrets:
      az_creds: ${{ secrets.AZURE_VM_CREDS }}
      az_vm_hostname: ${{ secrets.AZURE_VM_AUTHORITY }}
      az_vm_username: ${{ secrets.AZURE_VM_UN }}
      az_vm_password: ${{ secrets.AZURE_VM_UP }}
      certificate: ${{ secrets.CERTIFICATE }}
      certificate_password: ${{ secrets.CERTIFICATE_PASSWORD }}
    with:
      az_name: wsl-ci
      az_resource_group: wsl
      exec: |
        echo "Hello, world!"
        lsb_release -a
        ls -lAh