name: Example action using WSL

concurrency: azure-vm

on:
  pull_request:
     paths:
      # We run it when changing one if its dependencies
      - .github/workflows/wsl-example.yaml
      - .github/actions/**
  push:
    branches: [main]
  workflow_dispatch:

env:
  az_name: wsl-ci
  az_resource_group: wsl

jobs:
  vm-setup:
    # This job starts your Azure VM and opens up to RDP connections. It'll keep running
    # in the background to host RDP connections until the machine is stopped by stop-vm.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start Azure VM
        uses: ./.github/actions/vm-setup
        with:
          az_name: ${{ env.az_name }}
          az_resource_group: ${{ env.az_resource_group }}
          az_creds: ${{ secrets.AZURE_VM_CREDS }}
          az_vm_hostname: ${{ secrets.AZURE_VM_AUTHORITY }}
          az_vm_username: ${{ secrets.AZURE_VM_UN }}
          az_vm_password: ${{ secrets.AZURE_VM_UP }}

  run-script:
    # This job has an implicit dependency on start-vm, because the runner
    # won't be started until the VM is turned on. It must run concurrently with
    # vm-setup, so don't add an explicit depenendency.
    # Don't do this: needs: vm-setup
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install or update WSL
        uses: ./.github/actions/wsl-install
        with:
          distro: Ubuntu

      - name: Checkout your repo into WSL
        uses: ./.github/actions/wsl-checkout
        with:
          distro: Ubuntu
          working-dir: "~/myrepo"

      # You'll probably use this action if you program runs entirely inside WSL
      - name: Run bash inside WSL
        uses: ./.github/actions/wsl-bash
        with:
          distro: Ubuntu
          working-dir: "~/myrepo"
          exec: |
            echo "Hello from $(lsb_release -ds)"

      # You'll probably use this action if you program runs on Windows and uses WSL
      - name: Run powershell on Windows
        uses: ./.github/actions/wsl-powershell
        with:
          exec: |
            $env:WSL_UTF8=1 # Recommended otherwise it's hard to read on Github
            wsl --list --verbose

  stop-vm:
    # This action stops your Azure VM, hence stopping the RDP connection as well.
    runs-on: ubuntu-latest
    needs: run-script
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stop Azure VM
        uses: ./.github/actions/vm-stop
        with:
          az_name: ${{ env.az_name }}
          az_resource_group: ${{ env.az_resource_group }}
          az_creds: ${{ secrets.AZURE_VM_CREDS }}