name: Example action using WSL

concurrency: azure-vm

on:
  pull_request:
     paths:
      # We run it when changing one if its dependencies
      - .github/workflows/wsl-exec-example.yaml
      - .github/actions/wsl_enabled_powershell/action.yaml
      - .github/actions/wsl-exec/action.yaml
  push:
    branches: [main]
  workflow_dispatch:

env:
  az_name: wsl-ci
  az_resource_group: wsl

jobs:
  vm-setup:
    # This job starts your Azure VM and opens up to RDP connections. It'll keep running
    # in the background to host RDP connections until the machine is stopped by stop-vm.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start Azure VM
        uses: ./.github/actions/setup_vm
        with:
          az_name: ${{ env.az_name }}
          az_resource_group: ${{ env.az_resource_group }}
          az_creds: ${{ secrets.AZURE_VM_CREDS }}
          az_vm_hostname: ${{ secrets.AZURE_VM_AUTHORITY }}
          az_vm_username: ${{ secrets.AZURE_VM_UN }}
          az_vm_password: ${{ secrets.AZURE_VM_UP }}

  run-script:
    runs-on: self-hosted
    # This job has an implicit dependency on start-vm, because the runner
    # won't be started until the VM is turned on. It'll run concurrently with
    # vm-setup.
    steps:
      - name: Install or update WSL
        uses: ./.github/actions/install-wsl
        with:
          distro_name: Ubuntu-Preview
          distro_launcher: ubuntupreview.exe
          distro_store_name: Ubuntu (Preview)

      - name: Run powershell on Windows
        # You'll probably use this action if you program runs on Windows and uses WSL
        uses: ./.github/actions/wsl_enabled_powershell
        with:
          exec: |
            # Your code here
            Write-Output "Hello, World!"

      - name: Run bash inside WSL
        # You'll probably use this action if you program runs entirely inside WSL
        uses: ./.github/actions/wsl-exec
        with:
          exec: |
            echo "Hello, world!"

  stop-vm:
    # This action stops your Azure VM, hence stopping the RDP hosting as well.
    runs-on: ubuntu-latest
    needs: run-script
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stop Azure VM
        uses: ./.github/actions/stop_vm
        with:
          az_name: ${{ env.az_name }}
          az_resource_group: ${{ env.az_resource_group }}
          az_creds: ${{ secrets.AZURE_VM_CREDS }}